language: csharp
solution: BetBuddy/BetBuddy.sln
branches:
  only:
    - master
    - dev
script: make build
notifications:
  email: false
install:
  - nuget restore BetBuddy/BetBuddy.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
