language: csharp
solution: BetBuddy/BetBuddy.sln
branches:
  only:
    - master
    - dev
script:
  - xbuild /p:Configuration=Release BetBuddy/BetBuddy.sln /p:TargetFrameworkVersion="4.5"
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./BetBuddy/BetBuddyTest/bin/Release/BetBuddyTest.dll
notifications:
  email: false
install:
  - nuget restore BetBuddy/BetBuddy.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
